[meta]
format = 1
name = "hero_body"
layer = "body"

[palette]
ref = "../../palettes/sample.hex"

[palette.map]
"." = "transparent"
0 = 1
1 = 2

[[frame]]
name = "hero_body_0"
kind = "key"
duration_ms = 83
data = '''
................
................
................
................
................
................
....00000000....
....11111111....
....11111111....
....11111111....
....11111111....
....11111111....
....11111111....
....00000000....
................
................
'''

[[frame]]
name = "hero_body_1"
kind = "key"
duration_ms = 83
data = '''
................
................
................
................
................
................
....00000000....
....11111111....
....11111111....
....11111111....
....11111111....
....11111111....
....11111111....
....00000000....
................
................
'''
